-- Create blogs table if it doesn't exist
create table if not exists public.blogs (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text unique not null,
  excerpt text,
  category text not null,
  cover_image_url text,
  content text,
  author_id uuid references auth.users(id),
  created_at timestamp with time zone default now()
);

-- Create leads table if it doesn't exist
create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  name text not null,
  company text,
  industry text,
  budget text,
  message text,
  status text default 'New',
  created_at timestamp with time zone default now()
);

-- Enable row level security (optional but recommended)
alter table public.blogs enable row level security;
alter table public.leads enable row level security;

-- Create policies for blogs (allow authenticated users to insert, update their own, and select all)
do $$
begin
    if not exists (select 1 from pg_policies where tablename = 'blogs' and policyname = 'Allow authenticated users to insert blogs') then
        create policy "Allow authenticated users to insert blogs"
        on public.blogs for insert
        to authenticated
        with check (true);
    end if;
    
    if not exists (select 1 from pg_policies where tablename = 'blogs' and policyname = 'Allow users to update their own blogs') then
        create policy "Allow users to update their own blogs"
        on public.blogs for update
        to authenticated
        using (auth.uid() = author_id);
    end if;
    
    if not exists (select 1 from pg_policies where tablename = 'blogs' and policyname = 'Allow public to select blogs') then
        create policy "Allow public to select blogs"
        on public.blogs for select
        to public
        using (true);
    end if;
end $$;

-- Create policies for leads (allow public to insert, and authenticated admins to select/update)
do $$
begin
    if not exists (select 1 from pg_policies where tablename = 'leads' and policyname = 'Allow public to insert leads') then
        create policy "Allow public to insert leads"
        on public.leads for insert
        to public
        with check (true);
    end if;
    
    if not exists (select 1 from pg_policies where tablename = 'leads' and policyname = 'Allow authenticated users to update leads') then
        create policy "Allow authenticated users to update leads"
        on public.leads for update
        to authenticated
        using (true);
    end if;
    
    if not exists (select 1 from pg_policies where tablename = 'leads' and policyname = 'Allow authenticated users to select leads') then
        create policy "Allow authenticated users to select leads"
        on public.leads for select
        to authenticated
        using (true);
    end if;
end $$;