-- Drop existing tables if they exist (to start fresh)
drop table if exists public.blogs cascade;
drop table if exists public.leads cascade;

-- Create blogs table
create table public.blogs (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text unique not null,
  excerpt text,
  category text not null,
  cover_image_url text,
  content text,
  author_id uuid references auth.users(id),
  created_at timestamp with time zone default now()
);

-- Create leads table
create table public.leads (
  id bigint generated by default as identity primary key,
  name text not null,
  company text,
  industry text,
  budget text,
  message text,
  status text default 'New',
  created_at timestamp with time zone default now()
);

-- Enable row level security (optional but recommended)
alter table public.blogs enable row level security;
alter table public.leads enable row level security;

-- Create policies for blogs (allow authenticated users to insert, update their own, and select all)
create policy "Allow authenticated users to insert blogs"
on public.blogs for insert
to authenticated
with check (true);

create policy "Allow users to update their own blogs"
on public.blogs for update
to authenticated
using (auth.uid() = author_id);

create policy "Allow public to select blogs"
on public.blogs for select
to public
using (true);

-- Create policies for leads (allow authenticated users to insert and update, and select all)
create policy "Allow authenticated users to insert leads"
on public.leads for insert
to authenticated
with check (true);

create policy "Allow authenticated users to update leads"
on public.leads for update
to authenticated
using (true);

create policy "Allow public to select leads"
on public.leads for select
to public
using (true);